### ISSUE TITLE
Author field in `package.json` is non-conformant with the standard

### ISSUE THREAD

**Issue by joaomlneto** [emmdim/EthereumMeasurements#1]
As per the [NPM documentation](https://docs.npmjs.com/files/package.json#people-fields-author-contributors), the author is either a JSON object with three attributes (name, email, website) or a string in the format *name <email> (website)*

The attribute in `package.json` does not conform to this:

https://github.com/emmdim/EthereumMeasurements/blob/f215bc099a1ecb80ce0b0b6df5cac69821c048ca/package.json#L17

I am available to fix it for you through a pull request.

**Comment by emmdim** [comment]
Fixed by 2ba7dcdd35e262499ee09aaa340561fc32c49d3f

**Comment by joaomlneto** [comment]
"Fixed" is an overstatement. You actually rejected the pull request 😛

**Comment by emmdim** [comment]
I made my commit. Dind't like yours.
